# Use postgres/example user/password credentials

services:

  db:
    image: postgres:17.5
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: fleetingtrails
      POSTGRES_PASSWORD: StudentPortal123!

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:8.0.0
    restart: always
    ports:
      - 6380:6379

