// <auto-generated />
using System;
using FleetingOffers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetingOffers.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019140753_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseAdditionalImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseEntityId")
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseEntityId");

                    b.HasIndex("ImageId");

                    b.ToTable("AdvertiseAdditionalImageEntity");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseAnalyticsEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<int>("Conversions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseId")
                        .IsUnique();

                    b.ToTable("AdvertiseAnalytics");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("AdvertiseCategories");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseDealTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdvertiseDealTypes");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DealTypeId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubCategoryId")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ThumbnailImageId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DealTypeId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("ThumbnailImageId");

                    b.ToTable("Advertises");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseIndustryEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("AdvertiseIndustries");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseLocationEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseEntityId")
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseEntityId");

                    b.HasIndex("LocationId");

                    b.ToTable("AdvertiseLocations");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseOwnerEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseId");

                    b.HasIndex("UserId");

                    b.ToTable("AdvertiseOwners");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseRelatedAdvertiseEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedAdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RelatedAdvertiseId");

                    b.ToTable("AdvertiseRelatedAdvertises");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseTagEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseEntityId")
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseEntityId");

                    b.ToTable("AdvertiseTags");
                });

            modelBuilder.Entity("FleetingOffers.Module.Auth.AuthOtpEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpValue")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuthOtps");
                });

            modelBuilder.Entity("FleetingOffers.Module.Auth.AuthTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceSignature")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEntityId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("FleetingOffers.Module.Auth.PasswordEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Passwords");
                });

            modelBuilder.Entity("FleetingOffers.Module.Auth.UserPermissionEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("PermissionString")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubRoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubRoleId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("FleetingOffers.Module.Campaign.CampaignAdvertiseEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampaignEntityId")
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseId");

                    b.HasIndex("CampaignEntityId");

                    b.ToTable("CampaignAdvertises");
                });

            modelBuilder.Entity("FleetingOffers.Module.Campaign.CampaignEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailImageId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("ThumbnailImageId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("FleetingOffers.Module.Location.LocationEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AddressText")
                        .HasColumnType("text");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Union")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Upazila")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Village")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberAuthProviderEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubscriberAuthProviders");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("AuthProviderUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordId")
                        .HasColumnType("text");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("bytea");

                    b.Property<string>("ProvideInfoId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PasswordId");

                    b.HasIndex("ProvideInfoId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberFavouriteAdvertiseEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdvertiseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiseId");

                    b.HasIndex("SubscriberId");

                    b.ToTable("SubscriberFavouriteAdvertises");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberInitialPreferenceCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriberEntityId")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberEntityId");

                    b.ToTable("SubscriberInitialPreferenceCategories");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberInitialPreferenceIndustryEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("IndustryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriberEntityId")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberEntityId");

                    b.ToTable("SubscriberInitialPreferenceIndustries");
                });

            modelBuilder.Entity("FleetingOffers.Module.Upload.UploadEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("NumberOfUsage")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Storage")
                        .HasColumnType("integer");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfileEmailEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationProfileEntityId")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationProfileEntityId");

                    b.ToTable("OrganizationProfileEmails");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageId")
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProfileImageId");

                    b.ToTable("OrganizationProfiles");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfileExtraImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationProfileEntityId")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("OrganizationProfileEntityId");

                    b.ToTable("OrganizationProfileExtraImages");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfilePhoneEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationProfileEntityId")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationProfileEntityId");

                    b.ToTable("OrganizationProfilePhones");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationSocialMediaEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationProfileEntityId")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationProfileEntityId");

                    b.ToTable("OrganizationSocialMedias");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsPasswordSet")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoggedIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordId")
                        .HasColumnType("text");

                    b.Property<int?>("RestrictedUserSubRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserSubRoleId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OtpId");

                    b.HasIndex("PasswordId");

                    b.HasIndex("UserSubRoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "fff84865-d3b5-498f-8c21-c6cce272ad06",
                            CreatedAt = new DateTime(2025, 10, 19, 14, 7, 53, 274, DateTimeKind.Utc).AddTicks(4465),
                            Email = "abtahitajwar@gmail.com",
                            FullName = "Abtahi Tajwar",
                            IsPasswordSet = false,
                            Role = 0,
                            Username = "abtahi_tajwar"
                        },
                        new
                        {
                            Id = "32e18904-ca93-45f8-8e20-0eaab671ef26",
                            CreatedAt = new DateTime(2025, 10, 19, 14, 7, 53, 274, DateTimeKind.Utc).AddTicks(4535),
                            Email = "samaheerzameel@gmail.com",
                            FullName = "Samaheer Zameel",
                            IsPasswordSet = false,
                            Role = 1,
                            Username = "samaheer_zameel"
                        },
                        new
                        {
                            Id = "070eab32-fbdb-4d79-a622-a591917ba029",
                            CreatedAt = new DateTime(2025, 10, 19, 14, 7, 53, 274, DateTimeKind.Utc).AddTicks(4545),
                            Email = "fleetingtrails@gmail.com",
                            FullName = "Fleeting Trails",
                            IsPasswordSet = false,
                            Role = 2,
                            Username = "fleeting_trails"
                        });
                });

            modelBuilder.Entity("FleetingOffers.Module.User.UserSubRoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("UserSubRoles");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseAdditionalImageEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseEntity", null)
                        .WithMany("AdditionalImages")
                        .HasForeignKey("AdvertiseEntityId");

                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseAnalyticsEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseEntity", "Advertise")
                        .WithOne("Analytics")
                        .HasForeignKey("FleetingOffers.Module.Advertise.AdvertiseAnalyticsEntity", "AdvertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseCategoryEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageId");

                    b.HasOne("FleetingOffers.Module.User.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseDealTypeEntity", "DealType")
                        .WithMany()
                        .HasForeignKey("DealTypeId");

                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseIndustryEntity", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId");

                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "ThumbnailImage")
                        .WithMany()
                        .HasForeignKey("ThumbnailImageId");

                    b.Navigation("Category");

                    b.Navigation("CoverImage");

                    b.Navigation("CreatedBy");

                    b.Navigation("DealType");

                    b.Navigation("SubCategory");

                    b.Navigation("ThumbnailImage");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseIndustryEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseLocationEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseEntity", null)
                        .WithMany("Locations")
                        .HasForeignKey("AdvertiseEntityId");

                    b.HasOne("FleetingOffers.Module.Location.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseOwnerEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseEntity", "Advertise")
                        .WithMany("Owners")
                        .HasForeignKey("AdvertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetingOffers.Module.User.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseRelatedAdvertiseEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseEntity", "RelatedAdvertise")
                        .WithMany("RelatedAdvertises")
                        .HasForeignKey("RelatedAdvertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedAdvertise");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseTagEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("AdvertiseEntityId");
                });

            modelBuilder.Entity("FleetingOffers.Module.Auth.AuthTokenEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.User.UserEntity", null)
                        .WithMany("Tokens")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("FleetingOffers.Module.Auth.UserPermissionEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.User.UserSubRoleEntity", "SubRole")
                        .WithMany("Permissions")
                        .HasForeignKey("SubRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubRole");
                });

            modelBuilder.Entity("FleetingOffers.Module.Campaign.CampaignAdvertiseEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseEntity", "Advertise")
                        .WithMany()
                        .HasForeignKey("AdvertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetingOffers.Module.Campaign.CampaignEntity", null)
                        .WithMany("CampaignAdvertises")
                        .HasForeignKey("CampaignEntityId");

                    b.Navigation("Advertise");
                });

            modelBuilder.Entity("FleetingOffers.Module.Campaign.CampaignEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageId");

                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "ThumbnailImage")
                        .WithMany()
                        .HasForeignKey("ThumbnailImageId");

                    b.Navigation("CoverImage");

                    b.Navigation("ThumbnailImage");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Auth.PasswordEntity", "Password")
                        .WithMany()
                        .HasForeignKey("PasswordId");

                    b.HasOne("FleetingOffers.Module.Subscriber.SubscriberAuthProviderEntity", "ProvideInfo")
                        .WithMany()
                        .HasForeignKey("ProvideInfoId");

                    b.Navigation("Password");

                    b.Navigation("ProvideInfo");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberFavouriteAdvertiseEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Advertise.AdvertiseEntity", "Advertise")
                        .WithMany()
                        .HasForeignKey("AdvertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetingOffers.Module.Subscriber.SubscriberEntity", "Subscriber")
                        .WithMany("FavouriteAdvertises")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertise");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberInitialPreferenceCategoryEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Subscriber.SubscriberEntity", null)
                        .WithMany("InitialPreferenceCategories")
                        .HasForeignKey("SubscriberEntityId");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberInitialPreferenceIndustryEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Subscriber.SubscriberEntity", null)
                        .WithMany("InitialPreferenceIndustries")
                        .HasForeignKey("SubscriberEntityId");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfileEmailEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.User.OrganizationProfileEntity", null)
                        .WithMany("ContactEmails")
                        .HasForeignKey("OrganizationProfileEntityId");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfileEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageId");

                    b.HasOne("FleetingOffers.Module.Location.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImageId");

                    b.Navigation("CoverImage");

                    b.Navigation("Location");

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfileExtraImageEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Upload.UploadEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("FleetingOffers.Module.User.OrganizationProfileEntity", null)
                        .WithMany("ExtraImages")
                        .HasForeignKey("OrganizationProfileEntityId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfilePhoneEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.User.OrganizationProfileEntity", null)
                        .WithMany("Phones")
                        .HasForeignKey("OrganizationProfileEntityId");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationSocialMediaEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.User.OrganizationProfileEntity", null)
                        .WithMany("SocialMedias")
                        .HasForeignKey("OrganizationProfileEntityId");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.UserEntity", b =>
                {
                    b.HasOne("FleetingOffers.Module.Auth.AuthOtpEntity", "Otp")
                        .WithMany()
                        .HasForeignKey("OtpId");

                    b.HasOne("FleetingOffers.Module.Auth.PasswordEntity", "Password")
                        .WithMany()
                        .HasForeignKey("PasswordId");

                    b.HasOne("FleetingOffers.Module.User.UserSubRoleEntity", "UserSubRole")
                        .WithMany()
                        .HasForeignKey("UserSubRoleId");

                    b.Navigation("Otp");

                    b.Navigation("Password");

                    b.Navigation("UserSubRole");
                });

            modelBuilder.Entity("FleetingOffers.Module.Advertise.AdvertiseEntity", b =>
                {
                    b.Navigation("AdditionalImages");

                    b.Navigation("Analytics");

                    b.Navigation("Locations");

                    b.Navigation("Owners");

                    b.Navigation("RelatedAdvertises");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FleetingOffers.Module.Campaign.CampaignEntity", b =>
                {
                    b.Navigation("CampaignAdvertises");
                });

            modelBuilder.Entity("FleetingOffers.Module.Subscriber.SubscriberEntity", b =>
                {
                    b.Navigation("FavouriteAdvertises");

                    b.Navigation("InitialPreferenceCategories");

                    b.Navigation("InitialPreferenceIndustries");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.OrganizationProfileEntity", b =>
                {
                    b.Navigation("ContactEmails");

                    b.Navigation("ExtraImages");

                    b.Navigation("Phones");

                    b.Navigation("SocialMedias");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.UserEntity", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("FleetingOffers.Module.User.UserSubRoleEntity", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
